source ~/.config/nvim/plugins.vim
source ~/.config/nvim/config/ale.vim
source ~/.config/nvim/config/coc.vim
source ~/.config/nvim/config/codi.vim
source ~/.config/nvim/config/emmet.vim
source ~/.config/nvim/config/fugitive.vim
source ~/.config/nvim/config/set.vim
source ~/.config/nvim/config/php.vim
source ~/.config/nvim/config/rainbow-parentheses.vim
source ~/.config/nvim/config/multiple-cursor.vim
source ~/.config/nvim/config/undotree.vim
lua require('agung-satria')
